### ISSUE TITLE
字体文件可能提供错了

### ISSUE THREAD

**Issue by manfeel** [Angelic47/FontChinese7x7#1]
你好！首先非常感谢你执着的精神，中国互联网有你更精彩！但是你的字体文件好像不对（安装之后貌似是某种黑体字），我在macOS 和 windows 10中均做过测试。

**Comment by Angelic47** [comment]
你好，这个字体安装之后，直接使用操作系统自带的字体查看器进行查看，确实是很像普通黑体字，甚至和普通字体看不出什么区别。
这个字体的特殊之处在于如果关闭该字体的抗锯齿(例如win7下直接使用gdi加载该字体绘制)，并选择使用8px大小进行绘制的时候，会呈现非常清晰的点阵效果。
另外据他人测试，使用pygame加载该字体，关闭抗锯齿，设定字体为8px后进行绘制，也能得到同样的效果。
请再做一次测试，如果结果依然错误，我将重新上传字体文件。

**Comment by Angelic47** [comment]
另外提醒，photoshop自带的文本工具因为有差值优化，也无法实现如readme文件中演示的效果，已经测试

**Comment by manfeel** [comment]
非常感谢你的回复，经过测试，确实如你所说，附上pygame测试代码：
```
#! /usr/bin/env python
# coding=utf8
import pygame

pygame.init()
w = 320
h = 240
screen = pygame.display.set_mode((w, h))
clock = pygame.time.Clock()
done = False

font = pygame.font.Font("/Users/manfeel/Downloads/guanzhi.ttf", 8)

text = font.render(u"你好，世界！", False, (0, 128, 0))

while not done:
    for event in pygame.event.get():
        if event.type == pygame.QUIT:
            done = True
        if event.type == pygame.KEYDOWN and event.key == pygame.K_ESCAPE:
            done = True
    
    screen.fill((255, 255, 255))
    screen.blit(text, ((w - text.get_width()) // 2, (h - text.get_height()) // 2))
    
    pygame.display.flip()
    clock.tick(60)
```
效果如下：
![t2](https://user-images.githubusercontent.com/3507614/108650060-a5118680-74f9-11eb-9a97-ef4df8510d77.png)

**Comment by Angelic47** [comment]
感谢提供pygame的测试脚本
